name: nomad-pack

on:
  push:
    paths:
      - 'ghost.nomad'
      - 'images/**'

jobs:
  setup-nomad-pack:
    runs-on: ubuntu-latest
    name: Run Nomad Pack
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG="leandroaurelio/ghost:${{ github.run_number }}"
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

          # Tag the image as 'latest'
          docker tag $IMAGE_TAG leandroaurelio/ghost:latest
          docker push leandroaurelio/ghost:latest

      - name: Replace Variables for Deploy
        run: |
          if [[ "${{ github.ref_name }}" == "bench" ]]; then
            NAMESPACE="${{ secrets.BENCH_NAMESPACE }}"
            SITE_URL="${{ secrets.BENCH_SITE_URL }}"
            PORT="${{ secrets.BENCH_PORT }}"
          elif [[ "${{ github.ref_name }}" == "master" ]]; then
            NAMESPACE="${{ secrets.PROD_NAMESPACE }}"
            SITE_URL="${{ secrets.PROD_SITE_URL }}"
            PORT="${{ secrets.PROD_PORT }}"
          else
            echo "Branch não reconhecida. Abortando."
            exit 1
          fi
  
          # Substituir os placeholders no arquivo ghost.nomad
          sed -i "s|__NAMESPACE__|$NAMESPACE|g" ghost.nomad
          sed -i "s|__SITE_URL__|$SITE_URL|g" ghost.nomad
          sed -i "s|__PORT__|$PORT|g" ghost.nomad

      - name: Deploy nomad
        uses: rluisr/nomad-actions@master

      - name: Deploy
        run: |
          export NOMAD_ADDR="https://nomad.leandroaurelio.com"

          # Substituir placeholders pelos secrets
          
          sed -i "s|__USER_MAIL__|${{ secrets.USER_MAIL }}|g" ghost.nomad
          sed -i "s|__USER_PASSWORD__|${{ secrets.USER_PASSWORD }}|g" ghost.nomad
          sed -i "s|__MYSQL_ROOT_PASSWORD__|${{ secrets.MYSQL_ROOT_PASSWORD }}|g" ghost.nomad
          sed -i "s|__MYSQL_DATABASE__|${{ secrets.MYSQL_DATABASE }}|g" ghost.nomad
          sed -i "s|__MYSQL_USER__|${{ secrets.MYSQL_USER }}|g" ghost.nomad
          sed -i "s|__MYSQL_PASSWORD__|${{ secrets.MYSQL_PASSWORD }}|g" ghost.nomad
          
          # Planeja o job e captura o Job Modify Index
          INDEX=$(nomad job plan ghost.nomad | awk '/Job Modify Index/ {print $4}')
          echo "Job Modify Index: $INDEX"

          # Executa o job com o índice capturado
          nomad job run -namespace=$NAMESPACE -check-index $INDEX ghost.nomad || echo "Erro transitório ignorado"

          # Aguarda até o deployment ser criado
          echo "Aguardando deployment ser registrado..."
          DEPLOYMENT_ID=$(nomad deployment status -namespace=bench | grep ghost-bench | awk '{print $1}')
          nomad deployment promote -namespace=$NAMESPACE $DEPLOYMENT_ID

          STATUS=$(nomad deployment status -namespace=bench $DEPLOYMENT_ID | grep -i Status | awk '{print $3}')
          while [ "$STATUS" != "successful" ]; do
            sleep 5
            STATUS=$(nomad deployment status -namespace=bench $DEPLOYMENT_ID | grep -i Status | awk '{print $3}')
          done          

          # Exibe o status do job
          nomad status -namespace=$NAMESPACE ghost-$NAMESPACE
        env:
          NOMAD_ADDR: "https://nomad.leandroaurelio.com"
